# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings:
  engines:
    keep_only:
      - 1337x
      - adobe stock
      - adobe stock audio
      - adobe stock video
      - alpine linux packages
      - anaconda
      - annas archive
      - arch linux wiki
      - artstation
      - askubuntu
      - bandcamp
      - bitbucket
      - cachy os packages
      - caddy.community
      - codeberg
      - crates.io
      - currency
      - dailymotion
      - ddg definitions
      - deezer
      - devicons
      - dictzone
      - discuss.python
      - docker hub
      - duckduckgo
      - duckduckgo images
      - duckduckgo news
      - duckduckgo videos
      - duckduckgo weather
      - emojipedia
      - findthatmeme
      - flickr
      - free software directory
      - genius
      - gentoo
      - gitea.com
      - github
      - github code
      - gitlab
      - goodreads
      - google
      - google images
      - google news
      - google scholar
      - google videos
      - hackernews
      - hoogle
      - imdb
      - imgur
      - lib.rs
      - library genesis
      - library of congress
      - lobste.rs
      - lucide
      - mankier
      - mastodon hashtags
      - mastodon users
      - matrixrooms
      - mdn
      - metacpan
      - minecraft wiki
      - mixcloud
      - mojeek images
      - mojeek news
      - nixos wiki
      - npm
      - nyaa
      - odysee
      - openalex
      - openclipart
      - openlibrary
      - openstreetmap
      - openverse
      - pdbe
      - peertube
      - pi-hole.community
      - pinterest
      - pixabay images
      - pixabay videos
      - pkg.go.dev
      - presearch
      - presearch images
      - presearch news
      - presearch videos
      - pub.dev
      - public domain image archive
      - pubmed
      - pypi
      - reddit
      - repology
      - reuters
      - rottentomatoes
      - rubygems
      - searchcode code
      - searchmysite
      - sepiasearch
      - soundcloud
      - sourcehut
      - springer nature
      - stackoverflow
      - steam 
      - superuser
      - svgrepo
      - tineye
      - tmdb
      - tokyotoshokan
      - tootfinder
      - unsplash
      - uxwing
      - vimeo
      - voidlinux
      - wallhaven
      - wiby
      - wikibooks
      - wikicommons.audio
      - wikicommons.files
      - wikicommons.images
      - wikicommons.videos
      - wikidata
      - wikinews
      - wikipedia
      - wikiquote
      - wikisource
      - wikispecies
      - wikiversity
      - wikivoyage
      - wiktionary
      - youtube
      - z-library

valkey:
  url: valkey://valkey:6379/0

general:
  debug: false
  instance_name: "ChadXNG"
  donation_url: "https://www.patreon.com/c/ingenarelNeoJesus"
  enable_metrics: false

ui:
  center_alignment: true
  theme_args:
    results_on_new_tab: true
    hotkeys: vim
    url: full

search:
  safe_search: 0
  favicon_resolver: ""
  max_page: 0
  default_lang: "en"

hostnames:
  replace:
    # '(.*\.)?youtube\.com$': 'yt.example.com'
    # '(.*\.)?youtu\.be$': 'yt.example.com'
    '(.*\.)?reddit(media)?\.com$': 'redlib.catsarch.com'
    '(.*\.)?redd\.it$': 'redlib.catsarch.com'
    '(www\.)?(twitter|x)\.com$': 'nitter.net'
    'genius.com$': 'intellectual.catsarch.com'
  remove:
    - 'deepwiki\.(com|org)' # ai bullshit
    - '.+\.ai' # 90% are ai bullshit, sorry Anguilla
    - 'nixos.wiki' # official wiki exists
    - 'elderscrolls.fandom.com' # fuck fandom UESP better
    - 'fallout.fandom.com' # community wiki better
    - 'minecraft.fandom.com' # official minecraft wiki better
    - 'grokipedia.com' # burn the shit down
  # low_priority:
  high_priority:
    - '(.*\.)?wikipedia.org$' # wikipedia my GOAT

server:
  limiter: false  # enable this when running the instance for a public usage on the internet
  image_proxy: true

categories_as_tabs:
  general:
  images:
  videos:
  audio:
  music:
  lyrics:
  movies:
  news:
  maps:
  packages:
  wikis:
  repos:
  code:
  dictionary:
  books:
  resources:
  files:
  gaming:
  piracy:
  forums:
  social media:

engines:
  - name: 1337x
    disabled: false
    categories: ["piracy"]
    weight: 2
    timeout: 10

  - name: adobe stock
    categories: ["images", "videos"]
    weight: 0.5
    disabled: false
    timeout: 10

  - name: adobe stock audio
    categories: ["audio"]
    weight: 0.5
    disabled: false
    timeout: 10

  - name: adobe stock video
    categories: ["videos"]
    weight: 0.5
    disabled: false
    timeout: 10

  - name: alpine linux packages
    categories: ["packages"]
    disabled: false
    timeout: 10

  - name: anaconda
    categories: ["packages"]
    disabled: false
    timeout: 10

  - name: annas archive
    categories: ["piracy", "books"]
    disabled: false
    timeout: 10

  - name: arch linux wiki
    categories: ["wikis"]
    weight: 2
    disabled: false
    timeout: 10

  - name: artstation
    categories: ["images"]
    disabled: false
    timeout: 10

  - name: askubuntu
    categories: ["forums"]
    disabled: false
    timeout: 10

  - name: bandcamp
    categories: ["music"]
    disabled: false
    timeout: 10

  - name: bitbucket
    categories: ["repos"]
    disabled: false
    timeout: 10

  - name: cachy os packages
    categories: ["packages"]
    disabled: false
    timeout: 10

  - name: caddy.community
    categories: ["forums"]
    disabled: false
    timeout: 10

  - name: codeberg
    categories: ["repos"]
    disabled: false
    timeout: 10

  - name: crates.io
    categories: ["packages"]
    disabled: false
    timeout: 10

  - name: currency
    categories: ["general"]
    disabled: false
    timeout: 10

  - name: dailymotion
    categories: ["videos"]
    disabled: false
    timeout: 10

  - name: ddg definitions
    categories: ["dictionary"]
    disabled: false
    timeout: 10

  - name: deezer
    categories: ["music"]
    disabled: false
    timeout: 10

  - name: devicons
    categories: ["images"]
    disabled: false
    timeout: 10

  - name: dictzone
    categories: ["dictionary"]
    disabled: false
    timeout: 10

  - name: discuss.python
    categories: ["forums"]
    disabled: false
    timeout: 10

  - name: docker hub
    categories: ["packages"]
    disabled: false
    timeout: 10

  - name: duckduckgo
    categories: ["general"]
    disabled: false
    timeout: 10

  - name: duckduckgo images
    categories: ["images"]
    disabled: false
    timeout: 10

  - name: duckduckgo news
    categories: ["news"]
    disabled: false
    timeout: 10

  - name: duckduckgo videos
    categories: ["videos"]
    disabled: false
    timeout: 10

  - name: duckduckgo weather
    categories: ["general"]
    disabled: false
    timeout: 10

  - name: emojipedia
    categories: ["images"]
    disabled: false
    timeout: 10

  - name: findthatmeme
    categories: ["images"]
    weight: 0.5
    disabled: false
    timeout: 10

  - name: flickr
    categories: ["images"]
    disabled: false
    timeout: 10

  - name: free software directory
    categories: ["repos"]
    disabled: false
    timeout: 10

  - name: genius
    categories: ["lyrics"]
    disabled: false
    timeout: 10

  - name: gentoo
    categories: ["wikis"]
    disabled: false
    timeout: 10

  - name: gitea.com
    categories: ["repos"]
    disabled: false
    timeout: 10

  - name: github
    categories: ["repos"]
    disabled: false
    timeout: 10

  - name: github code
    categories: ["code"]
    disabled: false
    timeout: 10

  - name: gitlab
    categories: ["repos"]
    disabled: false
    timeout: 10

  - name: goodreads
    categories: ["books"]
    disabled: false
    timeout: 10

  - name: google
    categories: ["general"]
    disabled: false
    timeout: 10

  - name: google images
    categories: ["images"]
    disabled: false
    timeout: 10

  - name: google news
    categories: ["news"]
    disabled: false
    timeout: 10

  - name: google scholar
    categories: ["resources"]
    disabled: false
    timeout: 10

  - name: google videos
    categories: ["videos"]
    disabled: false
    timeout: 10

  - name: hackernews
    categories: ["forums"]
    disabled: false
    timeout: 10

  - name: hoogle
    categories: ["packages"]
    disabled: false
    timeout: 10

  - name: imdb
    categories: ["movies"]
    disabled: false
    timeout: 10

  - name: imgur
    categories: ["images"]
    disabled: false
    timeout: 10

  - name: lib.rs
    categories: ["wikis"]
    disabled: false
    timeout: 10

  - name: library genesis
    categories: ["resources"]
    disabled: false
    timeout: 10

  - name: library of congress
    categories: ["resources"]
    disabled: false
    timeout: 10

  - name: lobste.rs
    categories: ["forums"]
    disabled: false
    timeout: 10

  - name: lucide
    categories: ["images"]
    disabled: false
    timeout: 10

  - name: mankier
    categories: ["wikis"]
    disabled: false
    timeout: 10

  - name: mastodon hashtags
    categories: ["social media"]
    disabled: false
    timeout: 10

  - name: mastodon users
    categories: ["social media"]
    disabled: false
    timeout: 10

  - name: matrixrooms
    categories: ["social media"]
    disabled: false
    timeout: 10

  - name: mdn
    categories: ["wikis"]
    disabled: false
    timeout: 10

  - name: metacpan
    categories: ["resources"]
    disabled: false
    timeout: 10

  - name: minecraft wiki
    categories: ["gaming", "wikis"]
    disabled: false
    timeout: 10

  - name: mixcloud
    categories: ["music"]
    disabled: false
    timeout: 10

  - name: mojeek images
    categories: ["images"]
    disabled: false
    timeout: 10

  - name: mojeek news
    # categories: ["general", "news"]
    categories: ["news"]
    disabled: false
    timeout: 10

  - name: nixos wiki
    categories: ["wikis"]
    disabled: false
    timeout: 10

  - name: npm
    categories: ["packages"]
    disabled: false
    timeout: 10

  - name: nyaa
    categories: ["piracy", "movies"]
    disabled: false
    timeout: 10

  - name: odysee
    categories: ["videos"]
    disabled: false
    timeout: 10

  - name: openalex
    categories: ["resources"]
    disabled: false
    timeout: 10

  - name: openclipart
    categories: ["images"]
    disabled: false
    timeout: 10

  - name: openlibrary
    categories: ["resources"]
    disabled: false
    timeout: 10

  - name: openstreetmap
    categories: ["maps"]
    disabled: false
    timeout: 10

  - name: openverse
    categories: ["general"]
    disabled: false
    timeout: 10

  - name: pdbe
    categories: ["general", "resources"]
    disabled: false
    timeout: 10

  - name: peertube
    categories: ["videos"]
    disabled: false
    timeout: 10

  - name: pi-hole.community
    categories: ["forums"]
    disabled: false
    timeout: 10

  - name: pinterest
    categories: ["images"]
    disabled: false
    timeout: 10

  - name: pixabay images
    categories: ["images"]
    disabled: false
    timeout: 10

  - name: pixabay videos
    categories: ["videos"]
    disabled: false
    timeout: 10

  - name: pkg.go.dev
    categories: ["packages"]
    disabled: false
    timeout: 10

  - name: presearch
    categories: ["general"]
    disabled: false
    timeout: 10

  - name: presearch images
    categories: ["images"]
    disabled: false
    timeout: 10

  - name: presearch news
    categories: ["news"]
    disabled: false
    timeout: 10

  - name: presearch videos
    categories: ["videos"]
    disabled: false
    timeout: 10

  - name: pub.dev
    categories: ["packages"]
    disabled: false
    timeout: 10

  - name: public domain image archive
    categories: ["images"]
    disabled: false
    timeout: 10

  - name: pubmed
    categories: ["resources"]
    disabled: false
    timeout: 10

  - name: pypi
    categories: ["packages"]
    disabled: false
    timeout: 10

  - name: reddit
    categories: ["forums"]
    disabled: false
    timeout: 10

  - name: repology
    categories: ["packages"]
    weight: 5
    disabled: false
    timeout: 10

  - name: reuters
    categories: ["news"]
    disabled: false
    timeout: 10

  - name: rottentomatoes
    categories: ["movies"]
    disabled: false
    timeout: 10

  - name: rubygems
    categories: ["packages"]
    disabled: false
    timeout: 10

  - name: searchcode code
    categories: ["code"]
    disabled: false
    timeout: 10

  - name: searchmysite
    categories: ["general"]
    disabled: false
    timeout: 10

  - name: sepiasearch
    categories: ["videos"]
    disabled: false
    timeout: 10

  - name: soundcloud
    categories: ["music"]
    disabled: false
    timeout: 10

  - name: sourcehut
    categories: ["repos"]
    disabled: false
    timeout: 10

  - name: springer nature
    categories: ["resources"]
    disabled: false
    timeout: 10

  - name: stackoverflow
    categories: ["forums"]
    disabled: false
    timeout: 10

  - name: steam 
    categories: ["gaming"]
    disabled: false
    timeout: 10

  - name: superuser
    categories: ["forums"]
    disabled: false
    timeout: 10

  - name: svgrepo
    categories: ["images"]
    disabled: false
    timeout: 10

  - name: tineye
    categories: ["images"]
    disabled: false
    timeout: 10

  - name: tmdb
    categories: ["movies"]
    disabled: false
    timeout: 10

  - name: tokyotoshokan
    categories: ["piracy", "movies"]
    disabled: false
    timeout: 10

  - name: tootfinder
    categories: ["social"]
    disabled: false
    timeout: 10

  - name: unsplash
    categories: ["images"]
    disabled: false
    timeout: 10

  - name: uxwing
    categories: ["images"]
    disabled: false
    timeout: 10

  - name: vimeo
    categories: ["videos"]
    disabled: false
    timeout: 10

  - name: voidlinux
    categories: ["wikis"]
    disabled: false
    timeout: 10

  - name: wallhaven
    categories: ["images"]
    disabled: false
    timeout: 10

  - name: wiby
    categories: ["general"]
    disabled: false
    timeout: 10

  - name: wikibooks
    categories: ["books"]
    disabled: false
    timeout: 10

  - name: wikicommons.audio
    categories: ["audio"]
    disabled: false
    timeout: 10

  - name: wikicommons.files
    categories: ["files"]
    disabled: false
    timeout: 10

  - name: wikicommons.images
    categories: ["images"]
    disabled: false
    timeout: 10

  - name: wikicommons.videos
    categories: ["videos"]
    disabled: false
    timeout: 10

  - name: wikidata
    categories: ["resources"]
    disabled: false
    timeout: 10

  - name: wikinews
    categories: ["news"]
    disabled: false
    timeout: 10

  - name: wikipedia
    categories: ["wikis"]
    weight: 2
    disabled: false
    timeout: 10

  - name: wikiquote
    categories: ["resources"]
    disabled: false
    timeout: 10

  - name: wikisource
    categories: ["resources"]
    disabled: false
    timeout: 10

  - name: wikispecies
    categories: ["resources"]
    disabled: false
    timeout: 10

  - name: wikiversity
    categories: ["resources"]
    disabled: false
    timeout: 10

  - name: wikivoyage
    categories: ["resources"]
    disabled: false
    timeout: 10

  - name: wiktionary
    categories: ["resources"]
    disabled: false
    timeout: 10

  - name: youtube
    categories: ["videos"]
    disabled: false
    timeout: 10

  - name: z-library
    categories: ["books", "piracy"]
    disabled: false
    timeout: 10
